name: Codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codecov:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests with coverage
      run: npm run test:cov
    
    - name: Verify coverage file
      run: |
        echo "Checking coverage directory:"
        ls -la coverage/
        echo "Checking lcov.info:"
        head -20 coverage/lcov.info
        echo "File size:"
        wc -l coverage/lcov.info
    
    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./
        clean: true
        search_path: ./
        root_dir: ./
